### ISSUE TITLE
Inconsistent Page schema

### ISSUE THREAD

**Issue by AlexanderMishutkinP** [asistenti/iss-swagger-spec#3]
The page schema:
```
    PaginatedResponse:
      type: object
      properties:
        totalCount:
          type: integer
          format: integer
          example: 243
```
Is different from the Spring Page object and the way it is serialized
